version: '3.8'

services: 
  app:
    build:
      context: .
      target: ${STAGE:-builder}
    ports:
      - 3333:3333
    # volumes:
    #   - .:/home/node/app
    env_file:
      - .env.prod
    depends_on:
      - postgres

  postgres:
    container_name: fashion-store-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fashion-store
      - PGDATA=/data/postgres

  cache: 
    container_name: fashion-store-cache
    image: redis
    ports:
      - 6379:6379
